name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Publish --output ./Release

    - name: Stop Running Service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: sudo systemctl stop book-fair-api
        
    - name: Copy new Release folder into Server
      uses: easingthemes/ssh-deploy@main
      with:
        SOURCE: "Release"
        remote: "/var/www/book-fair-api"
        # This remote directory should be set for full read/write permission
        # sudo chmod 777 /path/to/directory
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_KEY }}
        
    - name: Start the Server and Log the Result
      uses: appleboy/ssh-action@master
      with:
        script: sudo systemctl start book-fair-api && sudo systemctl status book-fair-api
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
