name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Publish --output ./Release

    - name: Stop Running Service
      uses: garygrossgarten/github-action-ssh@v0.6.4
      with:
        command: sudo systemctl stop test
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
        
    - name: Copy new Release folder into Server
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./Release
        remote: /var/www/dotnetwebapi
        # This remote directory should be set for full read/write permission
        # sudo chmod 777 /path/to/directory
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
        
    - name: Start the Server and Log the Result
      uses: garygrossgarten/github-action-ssh@v0.6.4
      with:
        command: sudo systemctl start test && sudo systemctl status test
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
